const COST_CENTER = {
    NONE: "",
    HOUSE: "HOUSE",
    ADMINISTRATION: "ADMINISTRATION",
    SERVICE_CHARGES: "SERVICE_CHARGES",
    DWELLING: "DWELLING",
    BANKING: "BANKING",
    PRIVATE: "PRIVATE",
    DEPOSIT: "DEPOSIT",
    RENT: "RENT"
};


module.exports = COST_CENTER;